// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

import (
	"time"
)

// Defines values for ResourceProvisioningStatus.
const (
	Deprovisioning ResourceProvisioningStatus = "deprovisioning"
	Error          ResourceProvisioningStatus = "error"
	Provisioned    ResourceProvisioningStatus = "provisioned"
	Provisioning   ResourceProvisioningStatus = "provisioning"
	Unknown        ResourceProvisioningStatus = "unknown"
)

// KubernetesLabelValue A valid Kubenetes label value, typically used for resource names that can be
// indexed in the database.
type KubernetesLabelValue = string

// OrganizationScopedResourceReadMetadata defines model for organizationScopedResourceReadMetadata.
type OrganizationScopedResourceReadMetadata struct {
	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// Name A valid Kubenetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// OrganizationId The organization identifier the resource belongs to.
	OrganizationId string `json:"organizationId"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`
}

// ProjectScopedResourceReadMetadata defines model for projectScopedResourceReadMetadata.
type ProjectScopedResourceReadMetadata struct {
	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// Name A valid Kubenetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// OrganizationId The organization identifier the resource belongs to.
	OrganizationId string `json:"organizationId"`

	// ProjectId The project identifier the resource belongs to.
	ProjectId string `json:"projectId"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`
}

// ResourceMetadata Resource metadata valid for all API resource reads and writes.
type ResourceMetadata struct {
	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Name A valid Kubenetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`
}

// ResourceProvisioningStatus The provisioning state of a resource.
type ResourceProvisioningStatus string

// ResourceReadMetadata defines model for resourceReadMetadata.
type ResourceReadMetadata struct {
	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// Name A valid Kubenetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`
}

// ResourceWriteMetadata Resource metadata valid for all API resource reads and writes.
type ResourceWriteMetadata = ResourceMetadata
