// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xUX2/TMBD/KqdjDyCl3XhBIi/TJF4mQExjAolR0CW+NGaOndnndaXKd0dOuza00cT2",
	"zFtin+93vz/2CkvXtM6ylYD5CkNZc0P9500s2FsWDh+oYPOFTOS0rjiUXreincUcz+COjFbwPhbcF4NJ",
	"1Wk1cgaybHVJxiwhBlZQOQ+eg4u+ZLDUcACpSaAkCwV/t9oqvmcF2oLUDIqECgo8xQxbEmGfIH9cn0ze",
	"nk2+0eT37OVpvvub/JzOVifZm9fdoOLV6RFmKMuWMccgXts5dhk+TPGRhRLMIbPLhzmbTcmGaeJAxsDZ",
	"xfmOi2dSAcgqWHgtHPqJvWvZi+Zw0Hwf66rmXa/BVgZS6wCu/+llpDhvklm9PklBWGipoXGeoXRW+F6m",
	"Y3xTacI98lxhji+Od74fb0w/HnW868W6jdqzwvx63Wg2UPDCuzsdtLPazj8LSQzj/NpBHQQhYXAV0JZ3",
	"GpttbBJItDfWLexaxO2p4S8rzFDx3jZ77zzOHvH7kkkNPSdjPlWYXz+uzEFaumy152/pmRLbK93wuACi",
	"G+5t2zq9oAD9OVaJfeV8Q4I5KhKepPIxJxUbfg5Qf+4pQFqNt49W38ZB8/N3o4lrR3PxLyqPJGo/hTrZ",
	"/5fko4C7JLjiF5eC3Sx74jXvb/Z0GKGv6Yb/fzee926kZW0rh7mNxmToWrbUasxx/cbXYb3T/QkAAP//",
	"IMzP2JoGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
